language: node_js
node_js:
  - "8"

cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn test

deploy:
  provider: npm
  email: mark@larah.me
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true
    repo: sharkcore/tweenz